### ISSUE TITLE
ShouldNotHappenException happens

### ISSUE THREAD

**Issue by mbolli** [twigstan/twigstan#164]
I get this output:

```
Uncaught PHPStan\ShouldNotHappenException: Could not find Twig line number on /var/www/someproject/.twigstan/flattening/1/password_reset.html.twig.6bff259c.php:30. in /var/www/someproject/vendor/twigstan/twigstan/src/PHPStan/Collector/BlockContextCollector.php:91
#0 phar:///var/www/someproject/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/FileAnalyser.php(124): TwigStan\PHPStan\Collector\BlockContextCollector->processNode()
#1 phar:///var/www/someproject/vendor/phpstan/phpstan/phpstan.phar/src/Node/ClassStatementsGatherer.php(116): PHPStan\Analyser\FileAnalyser->PHPStan\Analyser\{closure}()
#2 phar:///var/www/someproject/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(614): PHPStan\Node\ClassStatementsGatherer->__invoke()
#3 phar:///var/www/someproject/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(495): PHPStan\Analyser\NodeScopeResolver::PHPStan\Analyser\{closure}()
#4 phar:///var/www/someproject/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(422): PHPStan\Analyser\NodeScopeResolver->processStmtNode()
#5 phar:///var/www/someproject/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(613): PHPStan\Analyser\NodeScopeResolver->processStmtNodes()
#6 phar:///var/www/someproject/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(422): PHPStan\Analyser\NodeScopeResolver->processStmtNode()
#7 phar:///var/www/someproject/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(751): PHPStan\Analyser\NodeScopeResolver->processStmtNodes()
#8 phar:///var/www/someproject/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(390): PHPStan\Analyser\NodeScopeResolver->processStmtNode()
#9 phar:///var/www/someproject/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/FileAnalyser.php(162): PHPStan\Analyser\NodeScopeResolver->processNodes()
#10 phar:///var/www/someproject/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/Analyser.php(64): PHPStan\Analyser\FileAnalyser->analyseFile()
#11 phar:///var/www/someproject/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyserRunner.php(62): PHPStan\Analyser\Analyser->analyse()
#12 phar:///var/www/someproject/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyseApplication.php(141): PHPStan\Command\AnalyserRunner->runAnalyser()
#13 phar:///var/www/someproject/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyseApplication.php(61): PHPStan\Command\AnalyseApplication->runAnalyser()
#14 phar:///var/www/someproject/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyseCommand.php(208): PHPStan\Command\AnalyseApplication->analyse()
#15 phar:///var/www/someproject/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Command/Command.php(259): PHPStan\Command\AnalyseCommand->execute()
#16 phar:///var/www/someproject/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(870): _PHPStan_e6dc705b2\Symfony\Component\Console\Command\Command->run()
#17 phar:///var/www/someproject/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(261): _PHPStan_e6dc705b2\Symfony\Component\Console\Application->doRunCommand()
#18 phar:///var/www/someproject/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(157): _PHPStan_e6dc705b2\Symfony\Component\Console\Application->doRun()
#19 phar:///var/www/someproject/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(114): _PHPStan_e6dc705b2\Symfony\Component\Console\Application->run()
#20 phar:///var/www/someproject/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(115): _PHPStan_e6dc705b2\{closure}()
#21 /var/www/someproject/vendor/phpstan/phpstan/phpstan(8): require('...')
#22 /var/www/someproject/vendor/bin/phpstan(119): include('...')
#23 {main}
```

password_reset.html.twig.6bff259c.php:30 is:
```php
 /**
     * @param array{} $context
     * @param array{} $blocks
     * @return iterable<null|scalar|\Stringable>
     */
    protected function doDisplay(array $context, array $blocks = []): iterable
    {
        $context += $this->env->getGlobals();
        $macros = $this->macros;
        yield from $this->getParent($context)->unwrap()->yield($context, \array_merge($this->blocks, $blocks)); // line 30
        yield from [];
    }
```

**Comment by ruudk** [comment]
Could you share the unmodified (don't touch the comments) compiled code snippet?

**Comment by ruudk** [comment]
I'm able to reproduce this. Will fix it.

**Comment by ruudk** [comment]
Thanks for your report. It's now [fixed](https://github.com/twigstan/twigstan/pull/166).

**Comment by mbolli** [comment]
thanks, superb support :)
